version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command:
      - /bin/sh
  build:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
      - GOOS=windows
    volumes:
      - .:/workspace
    working_dir: /workspace
    command:
      - go
      - build
      - -o
      - runsibling.exe
      - -ldflags
      - "-X main.version=${VERSION:-dev} -X main.commit=${COMMIT:-none}"
      - .
